const $=(s)=>document.querySelector(s);
const form=$('#translateForm'),titleInput=$('#songTitleInput'),artistInput=$('#artistInput'),langSelect=$('#sourceLanguageSelect'),lyricsInput=$('#lyricsInput'),charCount=$('#charCount'),message=$('#message'),resultList=$('#resultList'),translateButton=$('#translateButton'),clearButton=$('#clearButton'),feedbackButton=$('#feedbackButton'),statusPill=$('#statusPill'),apiSummary=$('#apiSummary');
const apiModal=$('#apiModal'),historyModal=$('#historyModal'),shareModal=$('#shareModal'),feedbackModal=$('#feedbackModal');
const providerSelect=$('#providerSelect'),modelInput=$('#modelInput'),modelSelect=$('#modelSelect'),modelDatalist=$('#modelDatalist'),baseUrlInput=$('#baseUrlInput'),apiKeyInput=$('#apiKeyInput'),saveKeyInput=$('#saveKeyInput'),apiState=$('#apiState'),fetchModelsButton=$('#fetchModelsButton');
const historyList=$('#historyList'),historyArtistFilter=$('#historyArtistFilter'),historyDirInput=$('#historyDirInput'),feedbackMeta=$('#feedbackMeta'),feedbackRating=$('#feedbackRating'),feedbackIssue=$('#feedbackIssue'),feedbackPreferred=$('#feedbackPreferred'),feedbackLineList=$('#feedbackLineList');
const prefFields=[...document.querySelectorAll('[data-preference]')],prefSummary=$('#preferenceSummary');
const providers={openai:{label:'OpenAI',baseUrl:'https://api.openai.com/v1',model:'gpt-5.4-mini',models:['gpt-5.4-mini','gpt-5.4','gpt-5.5','gpt-4.1-mini']},deepseek:{label:'DeepSeek',baseUrl:'https://api.deepseek.com/v1',model:'deepseek-chat',models:['deepseek-chat','deepseek-reasoner']},qwen:{label:'通义千问',baseUrl:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'qwen-plus',models:['qwen-plus','qwen-turbo','qwen-max']},moonshot:{label:'Moonshot',baseUrl:'https://api.moonshot.cn/v1',model:'moonshot-v1-8k',models:['moonshot-v1-8k','moonshot-v1-32k']},zhipu:{label:'智谱 GLM',baseUrl:'https://open.bigmodel.cn/api/paas/v4',model:'glm-4-flash',models:['glm-4-flash','glm-4-plus']},custom:{label:'自定义',baseUrl:'',model:'',models:[]}};
const keys={api:'lyrics-translator-api-profiles-public',hist:'lyrics-translator-history',pref:'lyrics-translator-preferences'};
const labels={purpose:{reading:'阅读',subtitle:'字幕',singing:'演唱',polished:'精修'},style:{literal:'直译',natural:'自然',lyrical:'歌词化'},faithfulness:{balanced:'均衡',faithful:'更忠实',adaptive:'更灵活'},chineseTone:{lyric:'中文歌词感',plain:'清楚直白',poetic:'更有诗意',spoken:'更口语'},emotionIntensity:{original:'保持原歌',restrained:'克制',intense:'浓烈'},lineLength:{match:'贴近原行',short:'短句',flexible:'自然可变'}};
let lines=[],notes=[],currentId='';
function msg(t,e=false){message.textContent=t;message.classList.toggle('error',e)}
function clean(t){return String(t||'').trim().replace(/\s+/g,' ')}
function cleanLyrics(t){return String(t||'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n').map(l=>l.replace(/\s+/g,' ').trim()).join('\n').replace(/\n{3,}/g,'\n\n').trim()}
function noPunc(t){return clean(t).replace(/[，,。．.、；;：:！？!?「」『』“”"‘’'（）()【】［］[\]《》<>…—–\-~～]/g,' ').replace(/\s+/g,' ').trim()}
function prefs(){const p={};for(const f of prefFields){if(f.dataset.preference)p[f.dataset.preference]=f.type==='checkbox'?f.checked:f.value}p.noPunctuation=true;return p}
function applyPrefs(p={}){for(const f of prefFields){const k=f.dataset.preference;if(k&&p[k]!=null){if(f.type==='checkbox')f.checked=!!p[k];else f.value=p[k]}}summarize()}
function savePrefs(){const p=prefs();localStorage.setItem(keys.pref,JSON.stringify(p));summarize();return p}
function summarize(){const p=prefs();prefSummary.textContent=[labels.purpose[p.purpose],labels.style[p.style],labels.faithfulness[p.faithfulness],labels.chineseTone[p.chineseTone],labels.emotionIntensity[p.emotionIntensity],labels.lineLength[p.lineLength],p.keepHookConsistent?'保留 hook':'',p.avoidOverExplain?'少解释':''].filter(Boolean).join(' · ')}
function readHist(){try{return JSON.parse(localStorage.getItem(keys.hist)||'[]')}catch{return[]}}
function writeHist(h){localStorage.setItem(keys.hist,JSON.stringify(h.slice(0,100)))}
function full(){return lines.map(l=>l.translation||'').join('\n')}
function renderEmpty(){lines=[];notes=[];currentId='';feedbackButton.disabled=true;resultList.className='result-list empty';resultList.innerHTML='<div class="empty-state"><strong>译文会显示在这里</strong><span>保持原歌词换行，逐行对照外文与中文。</span></div>'}
function renderLines(next,ns=[]){lines=(next||[]).map(l=>({source:String(l.source||''),translation:String(l.translation||'')}));notes=ns||[];feedbackButton.disabled=!full().trim();resultList.className='result-list';resultList.innerHTML='';if(notes.length){const n=document.createElement('div');n.className='notes-block';n.innerHTML='<strong>改写说明</strong><ul>'+notes.slice(0,5).map(x=>`<li>${x}</li>`).join('')+'</ul>';resultList.append(n)}for(const l of lines){const r=document.createElement('div');r.className='line-pair';const s=document.createElement('div');s.className='line-cell source'+(l.source?'':' blank');s.textContent=l.source;const tr=document.createElement('div');tr.className='line-cell translation'+(l.translation?'':' blank');tr.textContent=l.translation;r.append(s,tr);resultList.append(r)}}
function saveEntry(entry){const h=readHist();const item={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),createdAt:new Date().toISOString(),...entry};writeHist([item,...h]);currentId=item.id;return item}
function updateEntry(id,patch){writeHist(readHist().map(x=>x.id===id?{...x,...patch}:x))}
function getEntry(id){return readHist().find(x=>x.id===id)}
function apiConfig(){saveApi();return{provider:providerSelect.value,baseUrl:baseUrlInput.value.trim(),model:modelInput.value.trim(),apiKey:apiKeyInput.value.trim()}}
function populateModels(ms=[],preferred=''){const all=[...new Set([preferred,...ms].filter(Boolean))];modelSelect.innerHTML='';modelDatalist.innerHTML='';for(const m of all){modelSelect.add(new Option(m,m));const o=document.createElement('option');o.value=m;modelDatalist.append(o)}if(all[0]){modelInput.value=preferred||all[0];modelSelect.value=modelInput.value}}
function saveApi(){const c={provider:providerSelect.value,baseUrl:baseUrlInput.value,model:modelInput.value,saveKey:saveKeyInput.checked,apiKey:saveKeyInput.checked?apiKeyInput.value:''};localStorage.setItem(keys.api,JSON.stringify(c));const p=providers[c.provider]||providers.openai;apiSummary.textContent=`${p.label} / ${c.model||'未选择模型'}`;apiState.textContent=c.apiKey?'已保存到本机':apiKeyInput.value?'仅本次使用':'可用 .env.local'}
function loadApi(){let c={};try{c=JSON.parse(localStorage.getItem(keys.api)||'{}')}catch{}const p=providers[c.provider]||providers.openai;providerSelect.value=c.provider||'openai';baseUrlInput.value=c.baseUrl||p.baseUrl;modelInput.value=c.model||p.model;apiKeyInput.value=c.apiKey||'';saveKeyInput.checked=!!c.saveKey;populateModels(p.models,modelInput.value);saveApi()}
providerSelect.addEventListener('change',()=>{const p=providers[providerSelect.value]||providers.openai;baseUrlInput.value=p.baseUrl;modelInput.value=p.model;populateModels(p.models,p.model);saveApi()});for(const el of [modelInput,baseUrlInput,apiKeyInput,saveKeyInput]){el.addEventListener('input',saveApi);el.addEventListener('change',saveApi)}modelSelect.addEventListener('change',()=>{modelInput.value=modelSelect.value;saveApi()});
fetchModelsButton.addEventListener('click',async()=>{fetchModelsButton.disabled=true;fetchModelsButton.textContent='检索中...';try{const r=await fetch('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api:apiConfig()})});const d=await r.json();populateModels(d.models||[],modelInput.value||d.defaultModel);msg(`已加载 ${d.models?.length||0} 个模型${d.source==='remote'?'':'（内置列表）'}。`)}catch(e){msg(e.message,true)}finally{fetchModelsButton.disabled=false;fetchModelsButton.textContent='检索模型'}});
function renderHistory(){const h=readHist();const artists=[...new Set(h.map(x=>x.artist||'未填写歌手'))].sort();const cur=historyArtistFilter.value||'__all__';historyArtistFilter.innerHTML='<option value="__all__">全部歌手</option>'+artists.map(a=>`<option value="${a}">${a}</option>`).join('');historyArtistFilter.value=artists.includes(cur)?cur:'__all__';const list=h.filter(x=>historyArtistFilter.value==='__all__'||(x.artist||'未填写歌手')===historyArtistFilter.value);historyList.innerHTML=list.length?'':'<div class="history-empty">还没有保存记录。</div>';for(const x of list){const card=document.createElement('article');card.className='history-item';card.innerHTML=`<strong>${x.title||'未填写歌名'}</strong><span>${x.artist||'未填写歌手'} · ${x.sourceLanguage||'auto'} · ${new Date(x.createdAt).toLocaleString('zh-CN')}</span><p>偏好：${x.preferences?Object.values(x.preferences).slice(0,4).join(' · '):''}</p><p>${(x.fullTranslation||'').split('\n').filter(Boolean).slice(0,2).join(' / ')||'无译文'}</p><div class="history-actions"><button class="button ghost compact" data-a="load" data-id="${x.id}">打开</button><button class="button ghost compact" data-a="save" data-id="${x.id}">保存到本地历史库</button><button class="button ghost compact" data-a="download" data-id="${x.id}">下载 DOCX</button><button class="button ghost compact" data-a="retranslate" data-id="${x.id}">应用反馈重译</button><button class="button ghost compact" data-a="delete" data-id="${x.id}">删除</button></div>`;historyList.append(card)}}
function loadEntry(id){const x=getEntry(id);if(!x)return;titleInput.value=x.title||'';artistInput.value=x.artist||'';langSelect.value=x.sourceLanguage||'auto';lyricsInput.value=x.lyrics||'';currentId=x.id;applyPrefs(x.preferences||{});renderLines(x.lines||[],x.notes||[]);charCount.textContent=`${lyricsInput.value.length} 字`;historyModal.close();msg(`已打开历史记录：${x.title||'未填写歌名'}。`)}
historyList.addEventListener('click',async e=>{const b=e.target.closest('button[data-a]');if(!b)return;const id=b.dataset.id,a=b.dataset.a;if(a==='load')loadEntry(id);if(a==='delete'){writeHist(readHist().filter(x=>x.id!==id));renderHistory()}if(a==='retranslate'){loadEntry(id);form.requestSubmit()}if(a==='save'||a==='download'){const entry=getEntry(id);const r=await fetch('/api/history/save-docx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:a==='download'?'download':'save',historyDir:historyDirInput.value,entry})});if(a==='download'&&r.ok){const blob=await r.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${entry.artist||'歌手'} - ${entry.title||'歌名'}.docx`;link.click();URL.revokeObjectURL(url);msg('DOCX 已开始下载。')}else{const d=await r.json();msg(r.ok?`已保存：${d.filePath||d.filename}`:d.error,true)}}});
function ensureEntry(){let x=currentId&&getEntry(currentId);if(x)return x;if(!full().trim())return null;return saveEntry({title:clean(titleInput.value)||'未填写歌名',artist:clean(artistInput.value)||'未填写歌手',lyrics:cleanLyrics(lyricsInput.value),sourceLanguage:langSelect.value,preferences:prefs(),lines,notes,fullTranslation:full()})}
function openFeedback(){const x=ensureEntry();if(!x){msg('请先完成翻译，再填写反馈。',true);return}const f=x.feedback||{};feedbackMeta.textContent=`${x.artist||'未填写歌手'} · ${x.title||'未填写歌名'} · ${x.sourceLanguage||'auto'}`;feedbackRating.value=f.rating||0;feedbackIssue.value=f.issue||'';feedbackPreferred.value=f.preferred||'';feedbackLineList.innerHTML='';for(const [i,l] of lines.entries()){if(!l.source&&!l.translation)continue;const old=(f.lineFeedback||[]).find(v=>Number(v.index)===i)||{};const item=document.createElement('article');item.className='feedback-line-item';item.dataset.i=i;item.innerHTML=`<div class="feedback-line-text"><div><span>原词 ${i+1}</span>${l.source||' '}</div><div class="cur"><span>当前译文</span>${l.translation||' '}</div></div><div class="feedback-line-controls"><label class="feedback-line-field"><span>问题说明</span><textarea class="issue">${old.issue||''}</textarea></label><label class="feedback-line-field"><span>期望改法</span><textarea class="prefer">${old.preferred||''}</textarea></label><button class="button ghost compact" data-fa="adopt">直接采用</button><button class="button primary compact" data-fa="rewrite">按反馈调整</button></div>`;feedbackLineList.append(item)}feedbackModal.showModal()}
function readFb(){return{rating:Number(feedbackRating.value||0),issue:clean(feedbackIssue.value),preferred:clean(feedbackPreferred.value),lineFeedback:[...feedbackLineList.querySelectorAll('.feedback-line-item')].map(it=>{const i=Number(it.dataset.i);return{index:i,source:lines[i]?.source||'',currentTranslation:lines[i]?.translation||'',issue:clean(it.querySelector('.issue').value),preferred:noPunc(it.querySelector('.prefer').value)}}).filter(x=>x.issue||x.preferred)}}
function setLine(i,t){const v=noPunc(t);if(!v||!lines[i])return false;lines[i]={...lines[i],translation:v};renderLines(lines,notes);updateEntry(currentId,{lines,notes,fullTranslation:full(),feedback:readFb()});return true}
feedbackLineList.addEventListener('click',async e=>{const b=e.target.closest('button[data-fa]');if(!b)return;const it=b.closest('.feedback-line-item'),i=Number(it.dataset.i);if(b.dataset.fa==='adopt'){if(setLine(i,it.querySelector('.prefer').value))msg(`第 ${i+1} 行已采用。`);else msg('请先填写期望改法。',true)}else{const issue=it.querySelector('.issue').value,preferred=it.querySelector('.prefer').value;b.disabled=true;b.textContent='调整中...';try{const r=await fetch('/api/translate-line',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:lines[i].source,currentTranslation:lines[i].translation,issue,preferred,sourceLanguage:langSelect.value,preferences:prefs(),api:apiConfig()})});const d=await r.json();if(!r.ok)throw Error(d.error||'调整失败');setLine(i,d.translation);msg(`第 ${i+1} 行已调整。`)}catch(err){msg(err.message,true)}finally{b.disabled=false;b.textContent='按反馈调整'}}});
async function saveFeedback(){const x=ensureEntry(),f=readFb();if(!x)return;if(!f.rating&&!f.issue&&!f.preferred&&!f.lineFeedback.length){msg('请先填写评分或反馈内容。',true);return}const r=await fetch('/api/quality-feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,title:x.title,artist:x.artist,sourceLanguage:x.sourceLanguage,provider:x.provider,model:x.model,...f})});const d=await r.json();if(!r.ok){msg(d.error||'保存失败',true);return}updateEntry(x.id,{feedback:f,lines,notes,fullTranslation:full()});msg('反馈已保存。')}
form.addEventListener('submit',async e=>{e.preventDefault();const lyrics=cleanLyrics(lyricsInput.value);if(!lyrics){msg('请先粘贴外文歌词。',true);return}lyricsInput.value=lyrics;translateButton.disabled=true;translateButton.textContent='翻译中...';statusPill.textContent='正在翻译';const p=savePrefs();try{const r=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:clean(titleInput.value)||'未填写歌名',artist:clean(artistInput.value)||'未填写歌手',sourceLanguage:langSelect.value,lyrics,preferences:p,style:p.style,purpose:p.purpose,api:apiConfig()})});const d=await r.json();if(!r.ok)throw Error(d.error||'翻译失败');renderLines(d.lines||[],d.notes||[]);const saved=saveEntry({title:clean(titleInput.value)||'未填写歌名',artist:clean(artistInput.value)||'未填写歌手',lyrics,provider:d.provider,model:d.model,sourceLanguage:d.sourceLanguage||langSelect.value,purpose:d.purpose,style:d.style,preferences:d.preferences||p,lines,notes,fullTranslation:full()});currentId=saved.id;msg(`完成，识别为 ${d.sourceLanguage||langSelect.value||'外语'}，共 ${lines.length} 行。`)}catch(err){msg(err.message,true)}finally{translateButton.disabled=false;translateButton.textContent='开始翻译';statusPill.textContent='本地运行'}});
lyricsInput.addEventListener('input',()=>charCount.textContent=`${lyricsInput.value.length} 字`);clearButton.addEventListener('click',()=>{titleInput.value='';artistInput.value='';langSelect.value='auto';lyricsInput.value='';charCount.textContent='0 字';msg('');renderEmpty()});
$('#openApiModalButton').onclick=()=>apiModal.showModal();$('#closeApiModalButton').onclick=()=>apiModal.close();$('#saveApiModalButton').onclick=()=>{saveApi();apiModal.close();msg('API 接口配置已保存。')};$('#forgetKeyButton').onclick=()=>{apiKeyInput.value='';saveKeyInput.checked=false;saveApi();msg('已忘记 API Key。')};
$('#openHistoryButton').onclick=()=>{renderHistory();historyModal.showModal()};$('#closeHistoryButton').onclick=()=>historyModal.close();$('#clearHistoryButton').onclick=()=>{if(confirm('确定清空历史吗？')){writeHist([]);renderHistory()}};historyArtistFilter.onchange=renderHistory;
$('#openShareButton').onclick=async()=>{const list=$('#shareList');list.innerHTML='<div class="history-empty">正在读取地址...</div>';shareModal.showModal();try{const d=await (await fetch('/api/share-info')).json();list.innerHTML=(d.urls||[location.origin]).map(u=>`<div class="share-item"><a href="${u}" target="_blank">${u}</a><button class="button ghost compact" data-u="${u}">复制</button></div>`).join('')}catch{list.innerHTML='<div class="history-empty">读取失败。</div>'}};$('#closeShareButton').onclick=()=>shareModal.close();$('#shareList').onclick=e=>{const b=e.target.closest('button[data-u]');if(b)navigator.clipboard.writeText(b.dataset.u)};
feedbackButton.onclick=openFeedback;$('#closeFeedbackButton').onclick=()=>feedbackModal.close();$('#saveFeedbackButton').onclick=saveFeedback;
for(const f of prefFields){f.addEventListener('input',savePrefs);f.addEventListener('change',savePrefs)}
try{applyPrefs(JSON.parse(localStorage.getItem(keys.pref)||'{}'))}catch{summarize()}loadApi();renderEmpty();charCount.textContent='0 字';
